### ISSUE TITLE
`!pip install --user --upgrade pixiedust` fails

### ISSUE THREAD

**Issue by scottdangelo** [IBM/predictive-model-on-watson-ml#23]
```
Collecting pixiedust
Collecting astunparse (from pixiedust)
  Using cached https://files.pythonhosted.org/packages/8b/ea/d38686f1718e307d83673d905dcffd142640a31a217e4e76d1de78f21b20/astunparse-1.5.0-py2.py3-none-any.whl
Collecting geojson (from pixiedust)
  Using cached https://files.pythonhosted.org/packages/8d/39/231105abbfd2332f108cdbfe736e56324949fa9e80e536ae60a082cf96a9/geojson-2.4.0-py2.py3-none-any.whl
Collecting colour (from pixiedust)
  Using cached https://files.pythonhosted.org/packages/74/46/e81907704ab203206769dee1385dc77e1407576ff8f50a0681d0a6b541be/colour-0.1.5-py2.py3-none-any.whl
Collecting mpld3 (from pixiedust)
Collecting lxml (from pixiedust)
  Using cached https://files.pythonhosted.org/packages/eb/e2/02d18a1b3021b65409dd860f91cf0d68d79900f172bb3cc93cff21c3c951/lxml-4.2.5-cp35-cp35m-manylinux1_x86_64.whl
Collecting markdown (from pixiedust)
  Using cached https://files.pythonhosted.org/packages/6d/7d/488b90f470b96531a3f5788cf12a93332f543dbab13c423a5e7ce96a0493/Markdown-2.6.11-py2.py3-none-any.whl
Collecting wheel<1.0,>=0.23.0 (from astunparse->pixiedust)
  Using cached https://files.pythonhosted.org/packages/81/30/e935244ca6165187ae8be876b6316ae201b71485538ffac1d718843025a9/wheel-0.31.1-py2.py3-none-any.whl
Collecting six<2.0,>=1.6.1 (from astunparse->pixiedust)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Installing collected packages: wheel, six, astunparse, geojson, colour, mpld3, lxml, markdown, pixiedust
Exception:
Traceback (most recent call last):
  File "/opt/ibm/conda/miniconda3/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/ibm/conda/miniconda3/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/ibm/conda/miniconda3/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/opt/ibm/conda/miniconda3/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/opt/ibm/conda/miniconda3/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/opt/ibm/conda/miniconda3/lib/python3.5/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/opt/ibm/conda/miniconda3/lib/python3.5/site-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/opt/ibm/conda/miniconda3/lib/python3.5/distutils/command/install.py", line 251, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```

**Comment by scottdangelo** [comment]
Pip version:
```
pip 9.0.1 from /opt/ibm/conda/miniconda3/lib/python3.5/site-packages (python 3.5)

```
Current version is 18.0

**Comment by scottdangelo** [comment]
removing `--user` seems to get past this, and pixiedust appears to be working.
